### ISSUE TITLE
Missing updated journal reference/DOI.

### ISSUE THREAD

**Issue by eloisabentivegna** [Pizzuti92/MG-MAMPOSSt#2]
Dima & Vernizzi 2017 has now been published (https://journals.aps.org/prd/abstract/10.1103/PhysRevD.97.101302). Please update the article record, including its DOI.

(Part of JOSS review https://github.com/openjournals/joss-reviews/issues/4800)

**Comment by Pizzuti92** [comment]
Reference updated with the published one
