### ISSUE TITLE
Missing community guidelines.

### ISSUE THREAD

**Issue by eloisabentivegna** [Pizzuti92/MG-MAMPOSSt#3]
As part of the JOSS review (https://github.com/openjournals/joss-reviews/issues/4800), some guidelines for how the community can receive support using the package and contribute extensions must be present. Please add a section (on the README, for instance) explaining how to best interact with MG-MAMPOSSt's developer team.

**Comment by Pizzuti92** [comment]
I added a new sentence in the last section "Contacts, extension and update":

"For further information, to report issues and providing suggestions, as well as if you are interested in contributing to the development of the package, please contact Lorenzo Pizzuti (pizzuti@fzu.cz) or Andrea Biviano (andrea.biviano@inaf.it) on behalf of the developers team."
